# Generated by Django 5.1.2 on 2024-10-09 22:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipping', 'Shipping'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('partial_refund', 'Partially Refunded'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=63)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('payment_intent', models.CharField(blank=True, max_length=254, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=511, null=True)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.product')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.OrderItem', to='product.product', verbose_name='Products'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_intent'], name='orders_orde_payment_79a915_idx'),
        ),
    ]
