# Generated by Django 5.1 on 2024-10-06 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_items_orderitem_date_added_and_more'),
        ('product', '0009_product_stripe_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.CharField(default='stripe', max_length=50),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_intent'], name='orders_orde_payment_79a915_idx'),
        ),
    ]
