# Generated by Django 5.1 on 2024-10-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_secret',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
