# Generated by Django 5.1.2 on 2024-10-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_user_cartitem_unique_user_product'),
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(related_name='user', through='cart.CartItem', to='product.product', verbose_name=''),
        ),
    ]
