# Generated by Django 5.1.2 on 2024-10-09 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.CharField(max_length=254)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=1023, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success'), ('refunded', 'Refunded'), ('unconfirmed', 'UnConfirmed')], max_length=50)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=254, unique=True)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
