# Generated by Django 5.1 on 2024-10-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='stripe', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='provider',
            field=models.CharField(default='stripe', max_length=50),
        ),
    ]
