# Generated by Django 5.1 on 2024-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success'), ('refunded', 'Refunded')], default='success', max_length=50),
            preserve_default=False,
        ),
    ]
