# Generated by Django 5.1 on 2024-10-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_payment_customer_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success'), ('refunded', 'Refunded'), ('unconfirmed', 'UnConfirmed')], max_length=50),
        ),
    ]
