# Generated by Django 5.1.2 on 2024-10-09 22:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Quantity')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
