# Generated by Django 5.1.2 on 2024-11-10 06:37

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[product.validators.FileExtensionValidator(['png', 'svg', 'ico']), product.validators.LimitedFileSizeValidator(102400)]),
        ),
    ]
