# Generated by Django 5.1 on 2024-10-02 15:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_discount_product_date_modified_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='path',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
