# Generated by Django 5.1 on 2024-10-08 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
